SOL-112354: Start and termination of a RequestReplyMessageReceiver integration tests
SolaceDev/pubsubplus-go-client pull request #43
Opened 2024-03-06 14:57 UTC by oodigie

**Changes:**
- start and termination of a RequestReplyMessageReceiver integration tests

2024-03-06 17:12 UTC, cjwmorgan-sol requested changes
Looks like there is some use of time.Sleep again just like in PR #42.
Also noticed there seems to be a lack of lifecycle testing/expect statements around the replier.reply when receiver/service are no longer up.
Is that for another PR for testing? I would expect this to be in this PR as we need to check the behaviour of Replier.Reply when the receiver is terminated.
Git actions and jenkins have all request reply receiver testing passing which is great!

2024-03-06 17:12 UTC, cjwmorgan-sol commented on test/request_reply_message_receiver_test.go
> +						replier.Reply(helpers.NewMessage(messagingService, "Reply for: "+payload))
Is this missing an Expect statement on the error return from Reply.
Is there a test to verify a call to Replier.reply returns an error if the receiver is terminated or service is disconnected. As a part the lifecycle behaviour tests?

2024-03-07 13:12 UTC, oodigie commented on test/request_reply_message_receiver_test.go
> +			time.Sleep(100 * time.Millisecond)
I will explore this and push the updates

2024-03-12 15:41 UTC, cjwmorgan-sol approved these changes
Looks good to me and passing in git actions and jenkins2.
This is ready for merge.

2024-03-12 15:54 UTC, merged