SOL-62455: Feature add request reply messaging
SolaceDev/pubsubplus-go-client pull request #45
Opened 2024-03-15 19:52 UTC by cjwmorgan-sol

Adds request reply messaging publisher and receiver with unit tests and integration tests.

2024-03-27 19:30 UTC, oodigie requested changes
I left some comments for you @cjwmorgan-sol

2024-03-27 19:34 UTC, cjwmorgan-sol commented on internal/ccsmp/ccsmp_helper.h
> +    )
That is a bug and a very good catch.

2024-04-02 18:03 UTC, cjwmorgan-sol commented on internal/ccsmp/ccsmp_helper.h
> +    )
Raised internal solace jira issue SOL-115460. Determined the code was safe but the macro usage is unclear so commit: https://github.com/SolaceDev/pubsubplus-go-client/pull/45/commits/ac5e423e0b50393d5f2082409a50536199bc2c8f. Adds comments to the macro about the limitations. This macro is safe as the correlation id pointer from the native ccsmp client returns a null terminal utf8 string or is never called if the ccsmp client fails to extract a correlation id pointer.

2024-04-02 18:07 UTC, oodigie approved these changes
LGTM!

2024-04-25 14:31 UTC, merged