EBP-19: As a Solace Developer, I can use cache containers in integration testing
SolaceDev/pubsubplus-go-client pull request #72
Opened 2024-11-11 16:47 UTC by TrentDaniel

This PR includes the changes necessary to create cache instances, configure the broker to communicate with them, and use these cache instances during cache integration testing.
- [ ] The standard ginkgo command in an unconfigured environment does not cause cache tests to be run, and does not cause cache containers or configuration to be run
- [ ] The standard ginkgo command in an environment configured with the SOLCACHE_TEST_IMAGE variable set to any value will run the cache tests and run cache containers and configurations
- [ ] Running a specific test or group of tests that do not include cache does not cause cache containers or broker configurations for cache to be run
- [ ] Running a specific test or a group of tests that include cache in at least one test cause cache containers or configurations to be run
- [ ] The tests can create their own cache containers as a part of starting the test, run any configurations, and destroy those containers after the test has completed
- [ ] The name of the cache docker images as well as the docker registry where they are stored must not be committed to the repo
- [ ] The tests must have access to a solcacheproxy image to run those tests which require solcache proxy, and access to a solcache image to run those tests which require solcache. The env var SOLCACHEPROXY_TEST_IMAGE should be used in a similar way to SOLCACHE_IMAGE.
- [ ] The tests must be able to configure the broker for cache over SEMP
- [ ] A README must be provided to instruct the user on how to setup and run cache tests. This README must also communicate that the cache and cache proxy images are proprietary, and they will need to purchase them from the company to run the tests.
- [ ] All cache SEMP calls should be verified to work through manual inspection of the broker, and any notes on usage of these semp calls should be documented in a README for future developers to use.
- [ ] Verify that a cache request/response can be sent through the broker using sdkperf after the go test infrastructure has configured the broker for cache
- [ ] Verify that the broker configuration is consistent with the Python API broker configuration

2024-11-12 21:31 UTC, TrentDaniel commented on test/README.md
> +These environment variables are used to create and destroy the various docker containers that are required for testing. Modifying these variables after they have been used to create containers will l
change 'after test execution' with 'during execution'

2024-11-12 21:31 UTC, TrentDaniel commented on test/README.md
> +Cache tests can be run when using testcaontainers by exporting the variables:
fix typo

2024-11-12 21:32 UTC, TrentDaniel commented on test/README.md
> +PUBSUB_CACHE_HOSTNAME, and PUBSUB_CACHEPROXY_TEST_IMAGE are all necessary to run cache proxy tests. For tests that use both cache and cache proxy, all four variables are needed. Cache suspect is just
Make sure there are defaults for cache host name and suspect host name

2024-11-12 21:38 UTC, TrentDaniel commented on test/cache_test.go
> +                fmt.Println("Running cache test")
Remove println, add output as assertion failure instead

2024-11-12 21:45 UTC, TrentDaniel commented on test/helpers/semp_helpers.go
> +var True = testcontext.True
Duplicate comment

2024-11-12 21:47 UTC, TrentDaniel commented on test/testcontext/cache_util.go
> +func ConfigureDistributedCache(semp SEMPv2, msgVpnName string, distributedCache DistributedCacheConfig) error {
Change name to ConfigureDistributedCacheIfNotExists

2024-11-12 21:53 UTC, TrentDaniel commented on test/testcontext/cache_util.go
> +func (ctx *testContextCommon) waitForOperationalCache(timeout float64, state CacheOperationalState) error {
Pass time.Duration instead of float64

2024-11-12 21:58 UTC, cjwmorgan-sol reviewed
Did review together found minor issues please resolve comments.
Once jeknins autoamtion passes wiht changes this should be ready for merge.

2024-11-12 22:01 UTC, TrentDaniel commented on test/testcontext/test_context_testcontainers.go
> +    testFolderVar := os.Getenv(testFolderVarName)
Add comment explaining this

2024-11-13 16:42 UTC, cjwmorgan-sol requested changes
Needs one last change. To make the test code use more golang and avoid "python" like code.

2024-11-13 17:17 UTC, cjwmorgan-sol approved these changes
Changes look good to me.
Git actions are passing.

2024-11-13 18:25 UTC, merged